-- =============================================================================
-- Carga Histórica Oficial dos Certificados Emitidos (Turma Sicoob e anteriores)
-- Gerado automaticamente pelo migrador em 2026-09-16 12:56:32
-- Total de registros: 40
-- =============================================================================

SET FOREIGN_KEY_CHECKS = 0;

INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('6FB1ED64F19C8BBC4DA014D0AEAB6E78CC8D72A661523C23F01751D22CA998FD', 'Ana Luiza Santos Nascimento', '05536763180', '***.367.631-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 1, 1, 100, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": true, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 24, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('4A0E688EBAA089851E3AE438D01C256EDE3CD9EEA83CE149CA52029CB9633C75', 'Andressa Cristina Azevedo Arruda Rojas', '02744276138', '***.442.761-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 2, 2, 88, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": false, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 21, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('D2AA52935F73CC8170D7BC469A3FA8857C6DE3CA38138EE8AD893AEED2362F19', 'Carlos André Lins da Silva', '06292000176', '***.920.001-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 3, 3, 100, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": true, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 24, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('5179FF1FF00C8D8E7C3D13C93971F5C11BC3F6C5D0B70052A7F22FAE73FB2B18', 'Edicarme Romeiro de Souza', '97118931187', '***.189.311-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 4, 4, 100, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": true, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 24, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('E185F6162829B928343F12EA9E0D44A5ECE7C33CA829755410D648309BDD21B9', 'Eduardo Moreira Gonçalves', '06815966194', '***.159.661-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 5, 5, 100, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": true, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 24, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('95030B272539C30A7F8B34F96DF8326DE05C6BE906DC568FD84E94FB516ACBDB', 'Érica Miranda Amorim Mendes', '14168775763', '***.687.757-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 6, 6, 88, '4', '{\"(3h) 2026/jul/20\": false, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": true, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 21, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('2AC9A0873CDB2844DE1DB82C51101581214DC2FE2648E635242E4665C306DF69', 'Fernando Gomes de Sousa', '06695318123', '***.953.181-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 7, 7, 88, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": true, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": false}', 21, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('2783D5F7FDAC89DA1F736F264369B23B723AA5C4F3173D2B071266A1993AF466', 'Francisco das Chagas Rocha de Lima Junior', '01996022202', '***.960.222-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 8, 8, 75, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": false, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": true, \"(3h) 2026/ago/4\": false, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 18, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('02814EBE20BFBB340C10462E293817C543006586FB101CD63E9F2BAE2E8BEEE8', 'Gabriel Juan Alves de Fonte', '71171467109', '***.714.671-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 9, 9, 88, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": false, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": true, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 21, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('0B15A6FCE4EE201430F1519E034538F1CC59E073D0B123E170C7B12FD61211AA', 'Gabriela Pedó', '03934078109', '***.340.781-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 10, 10, 75, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": false, \"(3h) 2026/ago/4\": false, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 18, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('A62BBD36DADCA03C2B3078156A7BC6102B14D82A5CEB2FCB8BB6B7FC64B0EAE2', 'Gisele Aparecida Sales Andre', '11688003665', '***.880.036-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 11, 11, 100, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": true, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 24, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('6E5C52F8F314CEC64C767D901D4F0100CE649D3E7F0DA35857C21EDCC76002CD', 'Gislene Neves da Cruz', '01380008590', '***.800.085-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 12, 12, 88, '4', '{\"(3h) 2026/jul/20\": false, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": true, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 21, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('9C8270DCF6BD7C23F5E3CF14A4EC671180664E0DBA009D5EE575B7EEA8E47BCD', 'Gustavo Félix Queiroz', '83060383120', '***.603.831-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 13, 13, 100, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": true, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 24, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('8C3DD1696D0D77D4844FE1C4CE3C77AE63D22A20A4BDF29B723033BCAB82F923', 'Haphael Freitas Machiyama', '06708887100', '***.088.871-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 14, 14, 75, '4', '{\"(3h) 2026/jul/20\": false, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": false, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 18, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('67DAC119FC571F1F4AC89C1D452745AB24983F601E046199C369CAB789C6FAD9', 'Hávilla Luiza Aguiar Matos', '04412975100', '***.129.751-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 15, 15, 88, '4', '{\"(3h) 2026/jul/20\": false, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": true, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 21, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('67A37C14561F8093CC6E5980BDE54FAE3CCC975EDC414A8C27AF0E47C538B1AD', 'Ingred Diniz Rocha', '75667525100', '***.675.251-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 16, 16, 100, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": true, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 24, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('72BA33D0333325B0E761C1BB3CE53BE59FF64A0508BA3283C3A6A7D9512ECA1C', 'Janaina Nepomuceno', '11891168630', '***.911.686-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 17, 17, 100, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": true, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 24, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('E9B543DCD59C21DC98EEEFC8BE2F09EDAA76AC8D1794B9E286596055DB0ABED9', 'Janaina Paiva Mendes', '08743291678', '***.432.916-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 18, 18, 100, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": true, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 24, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('15319A7285D85442C3B4251A35243E0686502851527A66C377A0DC093801F26F', 'Jessica Leandro de Sousa', '01951256654', '***.512.566-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 19, 19, 100, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": true, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 24, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('407CCF0CAD4651D610E2D622E6F60DD34AAF27013C9071DE31F48C1916EB381A', 'João Victor Naves Oliveira Zica', '03453993152', '***.539.931-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 20, 20, 75, '4', '{\"(3h) 2026/jul/20\": false, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": false, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 18, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('88DB0CCB386E1958AB3748E3A88E046F59291667F670E32621EA433617F68FBD', 'Jordana Alecrim Silva', '70471425176', '***.714.251-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 21, 21, 88, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": false, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 21, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('5FC3AE5C9DD5C30C821F6B9B4B66B9D6BB70CF97E1F009BCB93998841FC8E042', 'Juliana Gonçalves da Silva', '03754439162', '***.544.391-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 22, 22, 100, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": true, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 24, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('90C765EF5BF14F77E26B6E79E353474AA24FAEDE3509FEEBD7664A47EF43DA64', 'Kallynne Aparecida Torres Oliveira', '02069706176', '***.697.061-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 23, 23, 75, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": false, \"(3h) 2026/ago/3\": false, \"(3h) 2026/ago/4\": false, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": false}', 18, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('AAB4CDF8C8986A953150F3BED97BEA830443DBEB64D378DB92EE5F0DAA0A3314', 'Laura Silva Oliveira', '71240656157', '***.406.561-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 24, 24, 88, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": true, \"(3h) 2026/ago/4\": false, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 21, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('361CD2A601EAF1A10B00EA33E9256FEB46108A48001D850FE15C99F0FA3255C5', 'Lucila Mariana Winck', '07783966144', '***.839.661-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 25, 25, 100, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": true, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 24, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('A354C9BFC569B8EB7B1E48AFB5CFE430E24948573F04C29188798625E08B71E4', 'Luiz Paulo de Oliveira Moura', '03471879196', '***.718.791-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 26, 26, 88, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": true, \"(3h) 2026/ago/4\": false, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 21, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('2A70A530BDA92D65F85E77BE8108DC73228D30924317C882BBC59EA2522AF244', 'Marcelo Silva', '94878412100', '***.784.121-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 27, 27, 100, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": true, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 24, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('3619EFFB7AF9A27616B77B1E9222F1DB9127D8ECF3C5997AA1D857144CA0687A', 'Maria Luiza de Oliveira', '71013941160', '***.139.411-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 28, 28, 75, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": false, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": false, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 18, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('091375C11D4E6BAB3FF1BF8449172DC446739A9DEBE78DCB896C8B54C63FE62B', 'Mariana Moreno da Silva Sampaio', '04646434148', '***.464.341-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 29, 29, 88, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": true, \"(3h) 2026/ago/4\": false, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 21, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('690764083C29E0760FCC700602FE1ED965F42CE2F7451D3EF6289320D1E126B0', 'Mariely Moreira Borges', '75056526134', '***.565.261-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 30, 30, 75, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": false, \"(3h) 2026/ago/3\": true, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": false}', 18, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('E3E0CAA9CD7E29BE1FDB9E1939BBB2729206709E542CD0B729C0AF484CD8D01E', 'Marília Santana Lima', '00829538135', '***.295.381-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 31, 31, 100, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": true, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 24, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('022C8EF3F1550470514F07B9DF3BE16D975E32D8F21C363F1141F6379637CD4B', 'Mayara Resende Leite Vilarinho', '70634116169', '***.341.161-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 32, 32, 88, '4', '{\"(3h) 2026/jul/20\": false, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": true, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 21, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('226F749E01ECD472546A4E6BAB7F7A7E15420EDD278BAA1FAAF2FCAD2BA8F27E', 'Paloma Amedomar dos Santos', '43348877830', '***.488.778-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 33, 33, 75, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": false, \"(3h) 2026/ago/3\": false, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 18, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('B1E64B6A8EE9F024D8CCB2EAEC8A9D8E840E428166AE7CB9FBAA358FB5CAD228', 'Paula Severo de Assis', '05000876105', '***.008.761-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 34, 34, 88, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": false, \"(3h) 2026/ago/3\": true, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 21, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('F798ABBBD10B037D55950DF8FE70F0C516D2262B85DB19DF16EF35E1E2EA38D7', 'Ruthy Gabrielly Ferreira da Silva', '71420817167', '***.208.171-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 35, 35, 88, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": false, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": true, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 21, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('E1DDAACE3051CA415EC0E8B278E6344E673A716626E5545ED95A5C58961D5BEB', 'Samara Belarmino Barbosa', '07243015182', '***.430.151-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 36, 36, 75, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": false, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": true, \"(3h) 2026/ago/4\": false, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 18, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('81CDE2626CD8B24E888BF6B555FAF42F35F4140DD72664A18F889F9947F015D5', 'Thais Cristina do Amaral Fontes', '10632775661', '***.327.756-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 37, 37, 100, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": true, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 24, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('D271D00217A854578A5009C080718A67CF5311B870136659EB878176FF4A3DB8', 'Vanessa Taube Stefanello', '07333976114', '***.339.761-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 38, 38, 100, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": true, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 24, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('944FF21008BDD5853AAD25B619CBE8310D486C62E8973F2BAA91E3E7BAF29FE6', 'Wisliane Lacir Aparecida Lima da Silva', '01922380270', '***.223.802-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 39, 39, 100, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": true, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 24, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`, `created_at`) VALUES ('0F1140EA4D5DF3E1F4549DE9FAFBD32E13E1D1246E95DC7710DD780FBDACD310', 'Yago Romário Santos Costa', '03695463180', '***.954.631-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 40, 40, 100, '4', '{\"(3h) 2026/jul/20\": true, \"(3h) 2026/jul/21\": true, \"(3h) 2026/jul/27\": true, \"(3h) 2026/jul/28\": true, \"(3h) 2026/ago/3\": true, \"(3h) 2026/ago/4\": true, \"(3h) 2026/ago/5\": true, \"(3h) 2026/ago/10\": true}', 24, 24, '2026-09-16 11:29:23') ON DUPLICATE KEY UPDATE `codigo_autenticidade` = VALUES(`codigo_autenticidade`);

SET FOREIGN_KEY_CHECKS = 1;
