-- =============================================================================
-- Banco de Produção Oficial: registros_certificados + tentativas_login
-- Gerado para promoção do Validador Público (ADR-0007 / Lote Sicoob: 40 registros)
-- Compatível com MariaDB 10.4+ / MySQL 8.0+ | Charset: utf8mb4
-- =============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `registros_certificados` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `turma_id` INT UNSIGNED NULL COMMENT 'Vinculação opcional com turma geradora',
    `codigo_autenticidade` VARCHAR(64) NOT NULL UNIQUE COMMENT 'Hash SHA-256 hexadecimal de 64 caracteres',
    `aluno_nome` VARCHAR(255) NOT NULL,
    `aluno_cpf` VARCHAR(14) NULL,
    `aluno_cpf_mascarado` VARCHAR(20) NULL,
    `curso_nome` VARCHAR(255) NOT NULL,
    `carga_horaria` INT UNSIGNED NOT NULL,
    `carga_horaria_extenso` VARCHAR(100) NULL,
    `data_inicio` VARCHAR(50) NULL,
    `data_conclusao` VARCHAR(50) NOT NULL,
    `data_emissao` VARCHAR(50) NOT NULL,
    `modalidade` VARCHAR(50) NOT NULL DEFAULT 'Presencial',
    `instrutor` VARCHAR(255) NULL,
    `cidade` VARCHAR(100) NULL,
    `ementa` TEXT NULL,
    `livro_numero` INT UNSIGNED NOT NULL,
    `folha_numero` INT UNSIGNED NOT NULL,
    `registro_numero` INT UNSIGNED NOT NULL,
    `frequencia` INT UNSIGNED NOT NULL DEFAULT 100,
    `lote_id` VARCHAR(50) NULL,
    `presencas_detalhadas` TEXT NULL,
    `horas_presentes` INT UNSIGNED NULL,
    `horas_totais` INT UNSIGNED NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY `uk_livro_folha_registro` (`livro_numero`, `folha_numero`, `registro_numero`),
    INDEX `idx_codigo_autenticidade` (`codigo_autenticidade`),
    INDEX `idx_aluno_nome` (`aluno_nome`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tentativas_login` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `ip_address` VARCHAR(45) NOT NULL,
    `username` VARCHAR(100) NOT NULL,
    `tentativas` INT UNSIGNED NOT NULL DEFAULT 1,
    `bloqueado_ate` TIMESTAMP NULL DEFAULT NULL,
    `ultimo_erro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_tentativas_ip_user` (`ip_address`, `username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('3A83BC60D234691233DE0DE8C194C72036AAF09CA27DD135AA47864D68229541', 'Ana Luiza Santos Nascimento', '05536763180', '***.367.631-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 1, 1, 100, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": true, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 24, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('BBFDB50F4996EF436AF08A007A9E63E377851E21DABE3B2B75D9DCDA2E16A8EA', 'Andressa Cristina Azevedo Arruda Rojas', '02744276138', '***.442.761-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 2, 2, 88, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": false, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 21, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('4CDED9A020F517EC8715185461A5012DCC08CCB1EBF77E5004FB686353A5270A', 'Carlos André Lins da Silva', '06292000176', '***.920.001-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 3, 3, 100, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": true, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 24, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('7C7D7D46C528782BB2059818D66C158E28754DD20714473120031FD9B4C50CA3', 'Edicarme Romeiro de Souza', '97118931187', '***.189.311-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 4, 4, 100, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": true, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 24, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('205546947B47E987D8BDDB4F995C3C2EE98B0D2AB9BBA689E03490AC10D68A69', 'Eduardo Moreira Gonçalves', '06815966194', '***.159.661-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 5, 5, 100, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": true, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 24, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('FD9856AC0D99DD8ACBC2E36B6B96B938217A7E69FE90EA4934E6DC48301EB01C', 'Érica Miranda Amorim Mendes', '14168775763', '***.687.757-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 6, 6, 88, 6, '{"(3h) 2026/jul/20": false, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": true, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 21, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('3D7F658BF30D58B499AE93D01FEEEED2F487B07DC3469B531C09BEC9C24C4E66', 'Fernando Gomes de Sousa', '06695318123', '***.953.181-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 7, 7, 88, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": true, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": false}', 21, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('71DC9EFFB4316013CF92820F43CEB5BEDF0124590982BDCAC4F041F25A24C440', 'Francisco das Chagas Rocha de Lima Junior', '01996022202', '***.960.222-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 8, 8, 75, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": false, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": true, "(3h) 2026/ago/4": false, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 18, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('0CC1515DBA620EC18EEC7C4CF31C5B5CB7DBB5DAAB1E776E2B47B07E6D9C0284', 'Gabriel Juan Alves de Fonte', '71171467109', '***.714.671-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 9, 9, 88, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": false, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": true, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 21, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('28D6E7AF5E25594B8BABEF0FE22BED3C66667523333EB35521409BF2FF49D667', 'Gabriela Pedó', '03934078109', '***.340.781-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 10, 10, 75, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": false, "(3h) 2026/ago/4": false, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 18, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('8219DBBDCAE7DEF6CC52538DD5048C551FF27A3922259D72A641D9A1F4032FA3', 'Gisele Aparecida Sales Andre', '11688003665', '***.880.036-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 11, 11, 100, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": true, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 24, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('87915466B8CA32C40D298DC12398D1578E1A9EFD073CBB943704AF2DCCE6B65A', 'Gislene Neves da Cruz', '01380008590', '***.800.085-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 12, 12, 88, 6, '{"(3h) 2026/jul/20": false, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": true, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 21, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('31D7B06961677699EC19C931955BDC65EE8A7465614DE8B10E48E582045AE07A', 'Gustavo Félix Queiroz', '83060383120', '***.603.831-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 13, 13, 100, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": true, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 24, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('7E86116DF33710872AD67DAB84463A75A58CD8FA6283A2E37D4CEA302DE5C931', 'Haphael Freitas Machiyama', '06708887100', '***.088.871-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 14, 14, 75, 6, '{"(3h) 2026/jul/20": false, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": false, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 18, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('E04E220CF1FEF01AE141F53CB1C141848B6A8679A2F795C4D6C9F05CF9689452', 'Hávilla Luiza Aguiar Matos', '04412975100', '***.129.751-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 15, 15, 88, 6, '{"(3h) 2026/jul/20": false, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": true, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 21, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('2122B6D2678BE8647D9FB6F3D27572437A9F48198EBAAE50B07B35BFB3C0D126', 'Ingred Diniz Rocha', '75667525100', '***.675.251-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 16, 16, 100, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": true, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 24, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('586E397EF6CE3E4DF9CCD1F36B929A319F862959D9F0570CC09FE43533E5A2C7', 'Janaina Nepomuceno', '11891168630', '***.911.686-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 17, 17, 100, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": true, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 24, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('FEF894FD8957EBCA128391CF5DA362DFE48B47E3837FC9B6C029711C6B31B4A5', 'Janaina Paiva Mendes', '08743291678', '***.432.916-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 18, 18, 100, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": true, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 24, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('8D9DE885CA6A57BF01777B57BC11DEA6DB04932614DB36F95727500E8A5F02BA', 'Jessica Leandro de Sousa', '01951256654', '***.512.566-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 19, 19, 100, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": true, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 24, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('6896426DF4FE958C5B089124365FC65C7361669F13B864294C65250AFBFF081C', 'João Victor Naves Oliveira Zica', '03453993152', '***.539.931-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 20, 20, 75, 6, '{"(3h) 2026/jul/20": false, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": false, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 18, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('FA9C95DEC472A6516A2A4FE819B01CACA452EF497A3BF6F7B65C6AF10B52CA04', 'Jordana Alecrim Silva', '70471425176', '***.714.251-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 21, 21, 88, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": false, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 21, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('48D91448A450C3ABC2531C77B15B2FAB67C988B39E6088EFE4978982E0DF761B', 'Juliana Gonçalves da Silva', '03754439162', '***.544.391-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 22, 22, 100, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": true, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 24, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('7FBE8F961161476C2D18C9F9511F284F02D69FCC27318C7B3FDC1791B5BB348A', 'Kallynne Aparecida Torres Oliveira', '02069706176', '***.697.061-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 23, 23, 75, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": false, "(3h) 2026/ago/3": false, "(3h) 2026/ago/4": false, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": false}', 18, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('F4BEA34055A9F1C44ACA87C2C0D2273BC2EC3D098CCC6153693A36665A24A9BA', 'Laura Silva Oliveira', '71240656157', '***.406.561-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 24, 24, 88, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": true, "(3h) 2026/ago/4": false, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 21, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('BE6AD0D877BBEBF913BC5027FD1F11E489C1651F201CB2FEABA2334D8F7387B1', 'Lucila Mariana Winck', '07783966144', '***.839.661-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 25, 25, 100, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": true, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 24, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('7F498E2E7E743CFC9317CF2E6C7BFF062B57933202A89339CEC2FC34DDEA0CD2', 'Luiz Paulo de Oliveira Moura', '03471879196', '***.718.791-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 26, 26, 88, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": true, "(3h) 2026/ago/4": false, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 21, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('2DFB9FCA3A6A3A193F5AF48169E6426145DF0DA324464DCAF678175D8FD5F995', 'Marcelo Silva', '94878412100', '***.784.121-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 27, 27, 100, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": true, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 24, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('4DD829CF87D79BADDCD77D9D684B28063CA7B36F7F75C7C46E4241DE2AD8E329', 'Maria Luiza de Oliveira', '71013941160', '***.139.411-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 28, 28, 75, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": false, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": false, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 18, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('EE153855DB530FFF6CF0EBAD7362953E5E73A8D359FB6CA43D3CECB7324AD813', 'Mariana Moreno da Silva Sampaio', '04646434148', '***.464.341-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 29, 29, 88, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": true, "(3h) 2026/ago/4": false, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 21, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('E7A724888E13D9CEAAC2F96B6F399981BFCDA612661670C5CCCFA08399C90459', 'Mariely Moreira Borges', '75056526134', '***.565.261-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 30, 30, 75, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": false, "(3h) 2026/ago/3": true, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": false}', 18, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('3E5FF0F3CB97F98BA8A030830937E0FD27F978EE0ACFFD5DAE412E7C9D98F78B', 'Marília Santana Lima', '00829538135', '***.295.381-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 31, 31, 100, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": true, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 24, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('1578CDC4F5A048A9AB44DE5ED782EC8688F1640D69DD43ADDBE05C6894556AFC', 'Mayara Resende Leite Vilarinho', '70634116169', '***.341.161-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 32, 32, 88, 6, '{"(3h) 2026/jul/20": false, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": true, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 21, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('AE7EF7D4D53A6304F6F5E32E2D71BC309657BC50EF4A115C9206C5F39ED5D819', 'Paloma Amedomar dos Santos', '43348877830', '***.488.778-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 33, 33, 75, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": false, "(3h) 2026/ago/3": false, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 18, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('DF19FD53AADE33C5E64605AAB681C15AA30AE2F486B27557FAC49071C4B73156', 'Paula Severo de Assis', '05000876105', '***.008.761-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 34, 34, 88, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": false, "(3h) 2026/ago/3": true, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 21, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('1587F67C963CBCD6E71C65903475E2AEE364C2CFED75BE24E93644F493C9D52A', 'Ruthy Gabrielly Ferreira da Silva', '71420817167', '***.208.171-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 35, 35, 88, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": false, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": true, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 21, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('C07FB51E3A69A6241868D697CD85DB796D7C9DAA5AD1B865CCA720ECF92DA46B', 'Samara Belarmino Barbosa', '07243015182', '***.430.151-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 36, 36, 75, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": false, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": true, "(3h) 2026/ago/4": false, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 18, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('DFBAF900B9EECE73203CA22FA555B7A183704118CD7DBA0D8AB6256E65539185', 'Thais Cristina do Amaral Fontes', '10632775661', '***.327.756-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 37, 37, 100, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": true, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 24, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('A3C2E669CBD42E82B58F32A61B49A52D0989BE0EAB25E1394D99F88C8E64EC32', 'Vanessa Taube Stefanello', '07333976114', '***.339.761-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 38, 38, 100, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": true, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 24, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('EA426BA5F543EA12C14E5B00477CDAFFF034D4E65AA908CF0C5EFAD7CB0A04B0', 'Wisliane Lacir Aparecida Lima da Silva', '01922380270', '***.223.802-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 39, 39, 100, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": true, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 24, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;
INSERT INTO `registros_certificados` (`codigo_autenticidade`, `aluno_nome`, `aluno_cpf`, `aluno_cpf_mascarado`, `curso_nome`, `carga_horaria`, `carga_horaria_extenso`, `data_inicio`, `data_conclusao`, `data_emissao`, `modalidade`, `instrutor`, `cidade`, `ementa`, `livro_numero`, `folha_numero`, `registro_numero`, `frequencia`, `lote_id`, `presencas_detalhadas`, `horas_presentes`, `horas_totais`) VALUES ('A79EF70DF201065091550B4A129D79A5A18A548909CEBEB11B3E264E9799DFCD', 'Yago Romário Santos Costa', '03695463180', '***.954.631-**', 'Excel Intermediário/Avançado', 24, 'vinte e quatro horas', '20/07/2026', '10/08/2026', '16/09/2026', 'Curso Livre de Capacitação Profissional', 'Tel Santana Leite', 'Goiânia', 'Módulo 1: Nivelamento, Organização de Bases e Produtividade no Excel — estruturação de dados em formato tabular, tabelas do Excel, filtros, segmentação de dados e boas práticas de produtividade;

Módulo 2: Fórmulas e Funções Intermediárias — funções lógicas e condicionais (SE, E, OU), funções de contagem e soma condicionais (CONT.SE, CONT.SES, SOMASE, SOMASES), referências absolutas, relativas e mistas;

Módulo 3: Funções de Busca e Análise de Dados — PROCV, PROCX e SEERRO aplicados a bases corporativas, tabela dinâmica e extração de indicadores;

Módulo 4: Tratamento de Dados e Matrizes Dinâmicas — funções de texto clássicas e modernas (ARRUMAR, EXT.TEXTO, TEXTOANTERS, TEXTODEPOIS, UNIRTEXTO), uso de curingas e funções matriciais (FILTRO, ÚNICO, TRANSPOR);

Módulo 5: Visualização, Automação e Transformação de Dados — formatação condicional avançada, gráficos para relatórios executivos, dashboards e introdução ao Power Query para importação, limpeza e transformação de bases.', 1, 40, 40, 100, 6, '{"(3h) 2026/jul/20": true, "(3h) 2026/jul/21": true, "(3h) 2026/jul/27": true, "(3h) 2026/jul/28": true, "(3h) 2026/ago/3": true, "(3h) 2026/ago/4": true, "(3h) 2026/ago/5": true, "(3h) 2026/ago/10": true}', 24, 24) ON DUPLICATE KEY UPDATE `codigo_autenticidade` = `codigo_autenticidade`;

SET FOREIGN_KEY_CHECKS = 1;
